"use client";
import { useEffect, useMemo, useState } from "react";
import type { Appointment, Provider, Service } from "@agenda/scheduling";
type Catalog = { services: Service[]; professionals: Provider[] };
type Form = {serviceId:string;providerId:string;date:string;time:string;name:string;phone:string;email:string;notes:string;whatsappConsent:boolean;privacyAccepted:boolean;website:string};
const initial: Form = {serviceId:"",providerId:"",date:"",time:"",name:"",phone:"",email:"",notes:"",whatsappConsent:false,privacyAccepted:false,website:""};
const labels = ["Serviço","Profissional","Data","Horário","Seus dados","Revisão"];
export function BookingFlow({initialCatalog}:{initialCatalog:Catalog}) {
  const [catalog,setCatalog]=useState<Catalog>(initialCatalog), [form,setForm]=useState<Form>(initial);
  const [step,setStep]=useState(0), [slots,setSlots]=useState<string[]>([]), [busy,setBusy]=useState(false), [error,setError]=useState(""), [done,setDone]=useState<Appointment|null>(null);
  useEffect(()=>{if(!initialCatalog.services.length)fetch("/api/catalog").then(r=>r.json()).then(setCatalog)},[initialCatalog.services.length]);
  const professionals=useMemo(()=>catalog.professionals.filter(p=>p.serviceIds.includes(form.serviceId)),[catalog,form.serviceId]);
  const service=catalog.services.find(s=>s.id===form.serviceId), professional=catalog.professionals.find(p=>p.id===form.providerId);
  const update=<K extends keyof Form>(key:K,value:Form[K])=>setForm(v=>({...v,[key]:value}));
  async function loadSlots(date:string) { update("date",date); update("time",""); setBusy(true); setError(""); try { const r=await fetch(`/api/availability?serviceId=${encodeURIComponent(form.serviceId)}&providerId=${encodeURIComponent(form.providerId)}&date=${date}`); const data=await r.json(); setSlots(data.slots||[]); } catch { if(process.env.NEXT_PUBLIC_VALIDATION_MODE==="1") setSlots(["09:00","09:30","10:00","13:30","14:00","15:30"]); else setError("Não foi possível consultar a agenda."); } setBusy(false); }
  async function submit() { setBusy(true); setError(""); try { const r=await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const data=await r.json(); if(!r.ok){setError(data.error);return;} setDone(data.appointment); } catch { if(process.env.NEXT_PUBLIC_VALIDATION_MODE==="1") setDone({token:"preview",reference:"DEMO-001",serviceId:form.serviceId,providerId:form.providerId,providerName:professional?.name||"Profissional disponível",start:`${form.date}T${form.time}:00-03:00`,customerName:form.name,phoneMasked:"••••••"+form.phone.replace(/\D/g,"").slice(-4),status:"CONFIRMED"}); else setError("Não foi possível concluir agora."); } finally { setBusy(false); } }
  if(done) return <section className="booking done"><span className="success">✓</span><p className="eyebrow">HORÁRIO CONFIRMADO</p><h1>Agendamento realizado.</h1><p>Guarde o código <strong>{done.reference}</strong>.</p><dl><div><dt>Profissional</dt><dd>{done.providerName}</dd></div><div><dt>Data e horário</dt><dd>{new Date(done.start).toLocaleString("pt-BR",{dateStyle:"long",timeStyle:"short"})}</dd></div></dl><a className="button" href={`/agendamento/gerenciar/${done.token}`}>Gerenciar agendamento</a></section>;
  return <section className="booking">
    <div className="progress"><span>Etapa {step+1} de 6</span><progress value={step+1} max={6}/></div>
    <p className="eyebrow">{labels[step].toUpperCase()}</p>
    {step===0&&<><h1>Qual serviço você procura?</h1><div className="choices">{catalog.services.map(s=><button key={s.id} className={form.serviceId===s.id?"selected":""} onClick={()=>update("serviceId",s.id)}><span><strong>{s.name}</strong><small>{s.description}</small></span><b>{s.durationMinutes} min</b></button>)}</div></>}
    {step===1&&<><h1>Com quem você prefere?</h1><div className="choices"><button className={form.providerId==="any"?"selected":""} onClick={()=>update("providerId","any")}><span><strong>Qualquer profissional disponível</strong><small>Escolha justa entre profissionais habilitados.</small></span></button>{professionals.map(p=><button key={p.id} className={form.providerId===p.id?"selected":""} onClick={()=>update("providerId",p.id)}><span><strong>{p.name}</strong><small>{p.bio}</small></span></button>)}</div></>}
    {step===2&&<><h1>Escolha uma data.</h1><label className="field">Data<input type="date" min={new Date().toLocaleDateString("en-CA")} value={form.date} onChange={e=>loadSlots(e.target.value)}/></label>{busy&&<p aria-live="polite">Consultando agenda…</p>}</>}
    {step===3&&<><h1>Qual horário funciona melhor?</h1>{slots.length?<div className="slots">{slots.map(s=><button className={form.time===s?"selected":""} key={s} onClick={()=>update("time",s)}>{s}</button>)}</div>:<p>Nenhum horário disponível para esta data.</p>}</>}
    {step===4&&<><h1>Seus dados para a reserva.</h1><div className="form-grid"><label className="field">Nome completo<input autoComplete="name" value={form.name} onChange={e=>update("name",e.target.value)}/></label><label className="field">WhatsApp<input inputMode="tel" autoComplete="tel" value={form.phone} onChange={e=>update("phone",e.target.value)}/></label><label className="field">E-mail (opcional)<input type="email" autoComplete="email" value={form.email} onChange={e=>update("email",e.target.value)}/></label><label className="field">Observação (opcional)<textarea maxLength={300} value={form.notes} onChange={e=>update("notes",e.target.value)}/></label><label className="check"><input type="checkbox" checked={form.whatsappConsent} onChange={e=>update("whatsappConsent",e.target.checked)}/> Aceito receber comunicações sobre este agendamento.</label><label className="check"><input type="checkbox" checked={form.privacyAccepted} onChange={e=>update("privacyAccepted",e.target.checked)}/> Li e aceito a política de privacidade.</label><input className="honeypot" tabIndex={-1} autoComplete="off" value={form.website} onChange={e=>update("website",e.target.value)}/></div></>}
    {step===5&&<><h1>Revise antes de confirmar.</h1><dl className="review"><div><dt>Serviço</dt><dd>{service?.name}</dd></div><div><dt>Profissional</dt><dd>{form.providerId==="any"?"Qualquer disponível":professional?.name}</dd></div><div><dt>Data</dt><dd>{form.date.split("-").reverse().join("/")}</dd></div><div><dt>Horário</dt><dd>{form.time}</dd></div><div><dt>Pagamento</dt><dd>No estabelecimento</dd></div></dl><p className="notice">O agendamento só será criado após você tocar em “Confirmar agendamento”.</p></>}
    {error&&<p className="error" role="alert">{error}</p>}
    <div className="actions">{step>0&&<button className="back" onClick={()=>setStep(s=>s-1)}>← Voltar</button>}<button className="button" disabled={busy||![Boolean(form.serviceId),Boolean(form.providerId),Boolean(form.date),Boolean(form.time),form.name.trim().length>=2&&form.phone.replace(/\D/g,"").length>=10&&form.privacyAccepted,true][step]} onClick={()=>step===5?submit():setStep(s=>s+1)}>{busy?"Aguarde…":step===5?"Confirmar agendamento":"Continuar →"}</button></div>
  </section>;
}
